### ISSUE TITLE
UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;

### ISSUE THREAD

**Issue by ben-manes** [bbottema/simple-java-mail#117]
I'm not sure what is causing this, but it began occurring for us today. I am not aware of any changes that would effect our emails, but thought you might have more insight on it.

```
javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;
        boundary="----=_Part_0_347165349.1510819320461"
        at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:896)
        at javax.activation.DataHandler.writeTo(DataHandler.java:317)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1652)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1824)
        at org.simplejavamail.converter.EmailConverter.mimeMessageToEML(EmailConverter.java:186)
        ... 12 common frames omitted
```

**Comment by bbottema** [comment]
I'm not sure, but it seems an issue with the underlying JavaMaip framework configuration. Specifically, the javax.activation package has issues recognizing mime types.

Are you explicitly including different versions of JavaMail or the activation library? Perhaps a mvn dependency:tree can give some insight.

Also, I found this clue to solving the problem: http://www.jguru.com/faq/view.jsp?EID=237257

It's not caused by Simple Java Mail though, it does not touch mime type registration of the underlying JavaMail framework.

**Comment by ben-manes** [comment]
Thanks for the tip. I had checked the dependency tree and played with excluding a few candidates. The JDK includes `javax.activation` without the default mailcap in the activation transitive dependency. Perhaps that is triggering it, so I added the mailcap configuration in your link's thread.

I also noticed this failed only when an email job failed, triggering a high priority email alert, and so on. All of the failures were internal alerts and not user-facing, perhaps cascading a bit. I'm not sure why the mime type would be anything but text/plain, since there are just the stack traces. Switching that to log if from a failed email and relying on Sentry notifications seemed to have silenced it.
