### ISSUE TITLE
Provide a way to handle success/failure in async mode (including testConnection())

### ISSUE THREAD

**Issue by trathschlag** [bbottema/simple-java-mail#148]
Hi!
It would be really useful if you could somehow handle success and failures when sending asynchronously. Is it be possible to implement [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) as a return value for `mailer.sendAsync(...)` or something?
I am interested to prepare a pull request.

Thanks in advance!

**Comment by bbottema** [comment]
Hmm, Simple Java Mail uses JDK 1.7, so it would need to be something else. Any preference?

Also, this issue will be solved another way with #121 when you can add custom steps in between the various stages of emailing (including handling exceptions). However, that won't be in the near future.

**Comment by bbottema** [comment]
I've added `Future` to the API for release 6.0.0. To use it:		
```
try {
	f.get(); // blocks
} catch (ExecutionException e) {
	System.err.println("Sending email failed");
	e.printStackTrace(System.err);
}
```
You can also implement your own (threaded) checking routine that checks `f.isDone()`  on mutliple emails in your batch so your thread doesn't block for individual async emails being sent (otherwise what's the point of sending asynchronously).

Would this suit your needs?

**Comment by trathschlag** [comment]
Hi, thanks for the reply!
I wanted to avoid `Future` as a solution, because there is no way to register a callback with it. You need to block or implement some polling mechanism, as you described.

Would it be possible to provide a basic interface
```java
interface MailCallback {
    void onSuccess();
    void onFailure(Exception e);
}
```
which the user can implement and pass into `mailer.sendAsync(callback)`?
This way everyone can write their own wrappers for integration with JDK8/Guava/Kotlin/etc...

**Comment by bbottema** [comment]
You got your wish @trathschlag!

Both sending emails and testing server connections can now be done asynchronously with either Future or Handlers.

#### Using Handlers
```java
AsyncResponse asyncResponse = mailer.sendMail(email, true);
// or: mailer.testConnection(email, true);

asyncResponse.onSuccess(() -> System.out.println("Success"));
asyncResponse.onException((e) -> System.err.println("error"));
```
#### Using Future
```java
Future<?> f = asyncResponse.getFuture();

// f.get() actually blocks until done, below is an example custom loop
// for checking result in a non-blocking way:
while (!f.isDone()) Thread.sleep(100);

// result is in, check it
try {
  f.get(); // without the above loop, this would actually block until done
  System.err.println("success");
} catch (ExecutionException e) {
  System.err.println("error");
}
```

**Comment by bbottema** [comment]
Released in 6.0.0-rc1!!

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.

**Comment by bbottema** [comment]
7.0.0 just released, which is a switch to Java8 and I've replaced this system with `CompletableFuture`.

**Comment by bbottema** [comment]
Current 9.x usage (verified against 9.3.2):

```java
mailer.sendMail(email, true)
    .whenComplete((unused, failure) -> {
        if (failure != null) {
            System.err.println(failure.getMessage());
        }
    });

mailer.testConnection(true)
    .whenComplete((unused, failure) -> {
        if (failure != null) {
            System.err.println(failure.getMessage());
        }
    });
```

`AsyncResponse`, its handlers, and `.getFuture()` were replaced by `CompletableFuture` in 7.0. Since 9.2, the returned future covers failures from the complete asynchronous operation; clear API mistakes such as a null email can still throw immediately. See the [7.0 migration](https://www.simplejavamail.org/migration-notes-7.0.0.html#completable-futures), [9.2 failure-reporting change](https://www.simplejavamail.org/migration-notes-9.2.0.html#async-failure-reporting), and [current async-result documentation](https://www.simplejavamail.org/features.html#section-handling-async-result).
