### ISSUE TITLE
SimpleMail not working with Gmail

### ISSUE THREAD

**Issue by hotmeatballsoup** [bbottema/simple-java-mail#23]
I have a GMail account and am trying to use GMail to send emails for my simple app:

    // Groovy pseudo-code
    static void main(String[] args) {
        Email email = new Email()
        email.setFromAddress("Me Myself", "myuser@example.com");
        email.setSubject("hey!!");
        email.addRecipient("Some One", "some1@example.com", RecipientType.TO);
        email.setText("We should meet up! ;)");
		
        Mailer mailer = new Mailer('smtp.gmail.com', 587, "mygmailuser@gmail.com", "mygmail+password",
            TransportStrategy.SMTP_TLS)
        Properties props = new Properties()
        props.put('mail.smtp.auth', 'true')
        props.put('mail.smtp.starttls.enable', 'true')
        mailer.applyProperties(props)
		
        mailer.sendMail(email)
    }

Produces:

    <large stack trace omitted for brevity>
    Caught: org.codemonkey.simplejavamail.MailException: Generic error: null
    org.codemonkey.simplejavamail.MailException: Generic error: null
        at org.codemonkey.simplejavamail.Mailer.sendMail(Mailer.java:269)
        at org.codemonkey.simplejavamail.Mailer$sendMail$0.call(Unknown Source)
        at com.me.myapp.Driver.main(Driver.groovy:38)
    Caused by: javax.mail.AuthenticationFailedException
        at org.codemonkey.simplejavamail.Mailer.sendMail(Mailer.java:261)
        ... 2 more

I've confirmed that my username/password are my correct gmail logins.  Any thoughts here?

**Comment by bbottema** [comment]
Hi @hotmeatballsoup, the transport strategy should be enough, no need for those extra properties. I have tested the following with success:

```java
final mail email = new Email();
email.setFromAddress("lollypop", "lol.pop@somemail.com");
email.addRecipient("C.Cane", "candycane@candyshop.org", RecipientType.TO);
email.setText("We should meet up!");
email.setTextHTML("<b>We should meet up!</b>");
email.setSubject("hey");
		
new Mailer("smtp.gmail.com", 25, "your user", "your password", TransportStrategy.SMTP_TLS).sendMail(email);
new Mailer("smtp.gmail.com", 587, "your user", "your password", TransportStrategy.SMTP_TLS).sendMail(email);
new Mailer("smtp.gmail.com", 465, "your user", "your password", TransportStrategy.SMTP_SSL).sendMail(email);
```

Make sure you try 

Possible causes:

 # You have two-factor authentication enabled in gmail, in which case you need to generate an application-specific password for your test ([Google App Passwords](https://security.google.com/settings/security/apppasswords))
 # Your credentials are not entered correctly (if I remember correctly, you should use your username, not your email (eg. `your.user` instead of `your.user@gmail.com`))
 # You are behind a proxy and the proxy is blocking you (but the exception doesn't seem to match this situation)
 # A router is blocking the outgoing ports (but again, the exception doesn't match)
