### ISSUE TITLE
Upgrade to Jakarta Mail 2.x.x

### ISSUE THREAD

**Issue by georgesolomon** [bbottema/simple-java-mail#295]
Jakarta Mail 2.0.0 release is the first release with package namespace changed to jakarta.mail. The main jar file is located at com.sun.mail:jakarta.mail.

This release contains no other enhancements nor bug fixes, except for the minimal required Java SE version which is now Java SE 8. This is also the release included in Jakarta EE 9. Applications are able to switch to this new version by just changing all imports that use javax.mail.* to instead use jakarta.mail.*.

**Comment by RakSrinaNa** [comment]
Will have to update `jakarta.activation` too.

I think that these dependencies will have to update to new namespace before:
* ` net.markenwerk:utils-mail-dkim`
* ` net.markenwerk:utils-mail-smime`
* `org.simplejavamail:smtp-connection-pool (because of com.github.bbottema:clustered-object-pool)`

**Comment by bbottema** [comment]
I have avoided switching to Java8 until now as Java7 still had a market share of around 5-10% until recently (off the top of my head). I'll do a new survey and see if a switch can be made more safely now...

**Comment by bluefireoly** [comment]
Could you please consider removing the low priority label from this?

An upgrade to version `2.0.0` or higher would be great, as other libraries already made that change, which leads to incompatibility for the following reason (illustrated in steps):

1. the other library has version 2.0.0 as a dependency, SimpleJavaMail has a lower version as a dependency 
2. the buildsystem now chooses the higher version automatically, meaning that the lower version won't be available as a library
3. now due to the change in the package structure, SimpleJavaMail can't access the required parts of jakarta mail anymore, as it expects them to be at `javax.mail` (where they aren't)

This means, that it currently is impossible to use SimpleJavaMail together with other libraries which implement a newer version of jakarta mail.

**Comment by bbottema** [comment]
I started migrating to Jakarta Mail 2.0.0. As https://github.com/markenwerk/java-utils-mail-smime is archived, I'm forking it so I can update the dependencies to Jakarta Mail 2.0.0 as well. I'll go ahead and merge some of my ignore pull requests as well, so I can clean up Simple Java Mail a bit finally.

**Comment by bbottema** [comment]
I'm in talks with the developers (both last one and original ones) to obtain permissions to relicense S/MIME under ApacheV2 and have procured 2 out of 3 permissions. When that's done, I'll start upgrading those projects.

**Comment by jhult** [comment]
@bbottema, any news on this?

**Comment by bbottema** [comment]
Yes, I've obtained all permissions and started migrating to Java 8 and Jakarta new version some time ago, but I put it on hold for some time to catch some breath. I've recently started picking up some maintenance work again to get back into the flow so I hope to pick this up again soon.

_Update, 6 September 2026:_ The written permissions and related correspondence are now preserved in the [`java-utils-mail-smime` repository](https://github.com/simple-java-mail/java-utils-mail-smime/blob/bdfe3be374c0ea1202aeff1a95ecfc6346f079dd/Relicensing%20approval%20by%20original%20authors.7z).

**Comment by bbottema** [comment]
Alright, things are looking up. I've upgraded everything to Java 8, Jakarta 2.0.1 and latest log4j version due to the recent security issues there. I've forked and migrated markenwerk DKIM and S/MIME to the Simple Java Mail space, with permissions of all parties involved and everything is not up to day and under ApacheV2 license.

**Comment by bbottema** [comment]
[7.0.0](https://github.com/bbottema/simple-java-mail/releases/tag/7.0.0) just released with the upgrade to Jakarta Mail 2.0.1
