### ISSUE TITLE
Can we Stamp Email, Recipient, AttachmentResource with no argument constructor class?

### ISSUE THREAD

**Issue by sthan001** [bbottema/simple-java-mail#296]
When we attempt to use these model directly on spring boot application rest endpoint, these models can't be used due to missing default constructor for jackson serialize/deserialization.

We don't want to duplicate these class attributes and transform up and down, can we make them available as usable once if you don't see any harm?

**Comment by bbottema** [comment]
There classes are *not* DTO's. They are specifically designed to contain only valid state by the way they can be created. Even if they currently look like a data class, I will reserve the right/freedom to change their behavior which might have side effects if treated as a DTO data class.

However, I might be able to support you by providing the dto classes you need, which can create the proper objects from their current content. However, I can never guarantee a successful creation of the corresponding proper classes, as I -by design- won't be able to control the contents of those dto's (your endpoints will be obviously). So your endpoints will need to be able to handle exceptions of type EmailException to make that work.

**Comment by sthan001** [comment]
Ignore the ask bbottema, looks email has lots of attributes and they all filled safely by your builder to avoid jakarta layer failures.
Again what ever you do on your builder the business layer has to do. No point in doing it.

Keep up good work!
