### ISSUE TITLE
Question: empty smtp username and password behaviour

### ISSUE THREAD

**Issue by VK-SMILECDR** [bbottema/simple-java-mail#333]
Hi @bbottema  

Thanks for the excellent and simple to use library

### Question
- Does SimpleJavaMail consider empty and not null smtp username and/or password as a requirement to authenticate mail client to mail server?
- Is this expected behaviour?

### Example
Based on the code review, the following looks like current logic in SimpleJavaMail:
- when the username is null no authentication required.
- when the username is empty and not null ("")  authentication required

**Comment by bbottema** [comment]
That's correct. If the user wouldn't want authentication, then username/password should be null, which seem the canonical principle to apply. I suppose it's technically possible to setup an authenticated SMTP server with empty values, which would be different from not having to authenticate at all. I could default empty username/password to mean the same as null-values, but I'm not sure that would make more sense.

Do you have reason to believe otherwise?

**Comment by bbottema** [comment]
Well that would be #331

**Comment by bbottema** [comment]
And so this change has been released in 6.7.4
