### ISSUE TITLE
Need help writing unit test for AsyncResponse

### ISSUE THREAD

**Issue by maheshwarigagan** [bbottema/simple-java-mail#355]
```
final AsyncResponse asyncResponse = mailer.sendMail(email, true);
if (asyncResponse == null) {
            //some code here
}
ayncResponse.onSuccess(() -> {// some code here}
asyncResponse.onException(ex -> {// some code here}
```
How do I make my code go to onSuccess/onException in a unit test case?
I have verified the email object to having the required properties. But onSuccess and onException we do some processing and I want to unit test them. Can you please provide a sample?

**Comment by bbottema** [comment]
Well for a junit test I wouldn't bother with async sending. Why would you want that?

**Comment by maheshwarigagan** [comment]
That async sending is part of the main code. I am trying to test it. Because onSuccess/onException has good amount of processing, I want to test those return values.

**Comment by bbottema** [comment]
Ok, well you have a bunch of options actually:

1. Obvious one: actually send an email using an SMTP server in test environment
2. Actually send an email locally using [Wiser](https://github.com/voodoodyne/subethasmtp/blob/master/Wiser.md), an in memory SMTP server for junit testing purposes. I created [my own Wiser Junit Rule](https://github.com/bbottema/simple-java-mail/tree/develop/modules/simple-java-mail/src/test/java/testutil/testrules) for that to easily integrate it in my tests. It works great.
3. Turn on [TransportModeLoggingOnly](https://www.simplejavamail.org/debugging.html#section-debug-mode) which only logs emails instead of sending them (but returns successfully)
4. Implement your [own sending logic](https://www.simplejavamail.org/features.html#section-custom-mailer) where you return with or without exception

Does that help?
