### ISSUE TITLE
Enhancement: Add support for OAUTH2 authentication

### ISSUE THREAD

**Issue by chris-cynation** [bbottema/simple-java-mail#421]
Hi,

I was wondering what OAuth2 support there is and if there are plans to support it if not.

**Comment by bbottema** [comment]
OAuth2... how? This is an SMTP library, it connects and authenticates with SMTP servers. I'm not sure where OAth2 comes into the picture here.

**Comment by neoxpert** [comment]
I guess this might be important as it is now required when connecting /authenticating to smtp.office365.com. At least the server response states ```250-AUTH LOGIN XOAUTH2``` and plain login using username and password does not work anymore. Also [gmail](https://developers.google.com/gmail/imap/xoauth2-protocol#smtp_protocol_exchange) does accept OAuth2 authentication.

So the question would be how to achieve this type of authentication with simple-java-mail assuming that there is a working OAuth2 token at hand.

**Comment by bbottema** [comment]
Interesting! Apparently, this was already possible in Sun JavaMail.

First of all, to start testing this in order to develop this feature:

Create a new Google API Project with new consent screen and OAuth client credentials, as described at [github.com/nfo/gmail_xoauth](https://github.com/nfo/gmail_xoauth).
Now generate a new OAuth2 token using these. The oauth2.py Python script from that repo is old and broken, but you can find new working instructions [here](https://shallowsky.com/blog/tech/email/gmail-api-oauth2.html), which uses a newer Python script from [getmail6](https://github.com/getmail6/getmail6).

**Comment by bbottema** [comment]
OAUTH2 authentication is now supported with the release of 7.6.0!

It's super simple, just use TransportStrategy.OAUTH2 (which is based on TransportStrategy.SMTP_TLS) and use your OAuth2 token as password.

**Comment by Venki028** [comment]
Hi @bbottema  i am trying to use the TransportStrategy.SMTP_OAUTH2 

i getting Exception saying 
Caused by: jakarta.mail.AuthenticationFailedException: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==   
;
  nested exception is:
        jakarta.mail.AuthenticationFailedException: OAUTH2 asked for more
Could you help if possible

**Comment by bbottema** [comment]
Current 9.x usage for a long-lived mailer (verified against 9.3.2):

```java
OAuth2AccessTokenProvider accessTokens = tokenService::currentAccessToken;

Mailer mailer = MailerBuilder
    .withSMTPServer("smtp.example.com", 587, "user@example.com")
    .withTransportStrategy(TransportStrategy.SMTP_OAUTH2)
    .withOAuth2AccessTokenProvider(accessTokens)
    .buildMailer();
```

Since 9.2, the refresh-aware provider is preferred for long-lived mailers because it is consulted before a physical SMTP connection is opened or reopened. Passing a fixed token as the SMTP password remains valid for a short-lived mailer. See the [9.2.0 release notes](https://github.com/bbottema/simple-java-mail/releases/tag/9.2.0) and [current OAuth2 documentation](https://www.simplejavamail.org/security.html#section-transport-strategy-oauth2).
