### ISSUE TITLE
Would be nice to add mock junit testing support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bbottema/simple-java-mail#5]
```
It would be nice to add a feature that performs all sorts of validations on the 
email, but stops short from actually delivering the email over the network.  
For unit testing purposes, etc.
```

Original issue reported on code.google.com by `trentj...@gmail.com` on 12 Jul 2012 at 1:50

**Comment by bbottema** [comment]
I've given this some thought. I think it would be a good addition as it allows me to test my own code better as well. I would probably not go with an interface, but a concrete class which allows you to override the default behavior.

Thoughts?

**Comment by musikele** [comment]
Hi @bbottema , 
in my unit tests I have succesfully used Wiser (https://github.com/voodoodyne/subethasmtp/blob/master/Wiser.md) and Wiser Assertions (https://github.com/kemitix/wiser-assertions) to test send. Maybe it could be of any help to you. 

For example: 
    @Before
    public void setup() {
        wiser = new Wiser();
        wiser.setPort(2500);
        wiser.start();
    }

    @Test
    public void shouldSendEmail() {
        ...
        WiserAssertions.assertReceivedMessage(wiser)
                .from("santa@claus.com")
                .to("obama@whitehouse.us")
                .withSubject("test mail")
                .withContentContains("duke nukem");
    }

this is my first piece of "markdown" so be indulgent .

**Comment by bbottema** [comment]
Your markdown if fine :) I edited so that it has java syntax highlighting now and you can see how easy that is.

Regarding your comment on Wiser, that's nice actually. I didn't know of it before.

**Comment by bbottema** [comment]
I've given this a lot of thought and I'm going to decline this feature, as mocking this library is not the right layer to mock.

Simple Java Mail is a simple pass-through solution translating high abstractions (Email instances) to low level Java Mail SMTP objects (MimeMessages etc.). You should test if your Email objects are being populated properly rather than if the messages being sent on low-level are populated properly. In the latter case you would simply be testing either Simple Java Mail itself or Oracle's SMTP implementation.

Simply mock a `Mailer` instance directly using something like EasyMock or some other library and test if `mailer.sendMail(Email)` is being invoked with the expected `Email` object.

For internal testing of Simple Java Mail, however, I might use WiserAssertions as suggested, but that is to test if Simple Java Mail works as expected and so it is unrelated to this issue here.

**Comment by bbottema** [comment]
Simple Java Mail now uses [Wiser](https://github.com/voodoodyne/subethasmtp) internally to test mail sending correctness!
