### ISSUE TITLE
Simple Java Mail should optionally be able to read properties from a Spring context

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#63]
It should be possible to optionally include a Spring bean from Simple Java Mail that can read properties from a Spring context and use these to configure Simple Java Mail (using the `ConfigLoader`).

**Comment by bbottema** [comment]
Released in 4.1.3.

**Comment by Flashky** [comment]
What about encrypting the password?
I really love the feature of reading the mailer configuration from the application.properties / yaml, but I find annoying that I cannot make my password encrypted in any way.

**Comment by Flashky** [comment]
I think I have read about that API before. I will try to use it and I'll let you know if it does work properly with SimpleJavaMail. Thank you. :)

**Comment by Flashky** [comment]
Hi bbottema!

I just wanted to share with you my discoveries, just in case you want to share the knowledge in the FAQ so other people know that it can be done easily. :)

I have a Spring Boot application, in order to make Jasypt work with the SimpleJavaMail password I just needed to do the following.

# Encrypting the password with Jasypt #

The first thing you would want to do is to encrypt the password.

It seems Jasypt provides some easy tools for encrypting a password using command line:
http://www.jasypt.org/cli.html
http://www.jasypt.org/download.html

After downloading and unziping the tool, just go to your terminal and execute either the bat or the sh just like this:

```bat
encrypt.bat input=<password_to_encrypt> password=<master_password_for_encryption>
```
The encrypted password will be shown at the output of the command.

# Project configuration #

1. pom.xml - Add the following dependency:

```xml
<dependency>
    <groupId>com.github.ulisesbocchio</groupId>
    <artifactId>jasypt-spring-boot-starter</artifactId>
    <version>2.1.0</version>
</dependency>
````

2. Properties file - Configure the master password for Jasypt:
```yaml
jasypt:
  encryptor:
    password: <master_password_for_encryption>
```
3. Properties file - Configure the encrypted password for SimpleJavaMail:

```yaml
simplejavamail:
  smtp:
    password: ENC(<encrypted_password>)
```

4. Spring Boot Application class - Add the following annotation:
```java
@EnableEncryptableProperties
```

And that's it! I didn't have to modify a single line of code, besides the annotation itself. Everything is pretty well configurable using just YAML properties. 

# Additional comments # 

I was a bit bugged that I stopped showing the SimpleJavaMail password and then started displaying the Jasypt password, so I researched a little bit further.

If you don't want to expose the jasypt encrypt password in the properties file, you can add the password as a VM argument:
```java
java -Djasypt.encryptor.password=password -jar target/jasypt-spring-boot-demo-0.0.1-SNAPSHOT.jar
```

Or just as a Environment System variable in the YAML:
```yaml
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}
```
