### ISSUE TITLE
Support custom SslSocketFactory

### ISSUE THREAD

**Issue by uschi2000** [bbottema/simple-java-mail#86]
Hi,
Perusing the code base, it seems there is no way to use a custom, explicitly provided SslSocketFactory with simple-java-mail, is that correct?

I'd like to do something of the following form:
```
TransportStrategy myTlsStrategy = TransportStrategy
  .from(TransportStrategy.SMTP_TLS)
  .sslSocketFactory(createMySslFactory())
  .build();
Mailer tlsMailer = new Mailer("host", port, null, null, myTlsStrategy);
```

Let me know if (a) this is possible today, or (b) if you're willing to take a PR to this effect.
Thanks! Robert.

**Comment by bbottema** [comment]
I suspect it's possible by configuring the ssl factory directly on the session object (the native JavaMail way). However, I would appreciate a pull request to make it easy with Simple Java Mail.

But I'm not sure about including it in the strategy, or as part of the ServerConfig object (check the other Mailer constructors. I'm on my phone still, otherwise I would have given an example of this.

**Comment by uschi2000** [comment]
I have gotten around the immediate need for TLS for the moment, but suspect I'll have to come back to this eventually. Feel free to close for now, @bbottema . (FYI, I tried something like this for about 3 mins, it didn't work and I gave up:

```
        Properties mailerProps = mailer.getSession().getProperties();
        mailerProps.put("mail.smtp.socketFactory.class", "my.CustomSslSocketFactory");
```
)
